site_name: MRS

repo_url: https://github.com/multirotorsociety/mrs-documentation
repo_name: mrs-documentation
edit_uri: ''

theme:
    name: material
    palette: 
        primary: light blue
        accent: blue
    font:
        text: Noto Sans
    features:
        - navigation.tabs
    icon:
        logo: material/quadcopter

nav:
    - Home: 'index.md'
    - Documentation:
        - Introduction to Drones: 'introduction_to_drones.md'
        - Introduction to Advanced Drones: 'introduction_to_advanced_drones.md'
        - AAVC Reference: 'AAVC_reference.md'

markdown_extensions:
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences